Sorter indikatorer
mong/mongts pull request #2283
Opened 2024-04-08 13:13 UTC by Stein-Kato

2024-04-11 12:33 UTC, larstun commented
@arnfinn er denne reviewed?

2024-04-11 14:04 UTC, arnfinn requested changes
Lurer på om ikke sorteringen er feil vei. Sjekket bare hjerneslag og da var det slik hos meg.

![image](https://github.com/mong/mongts/assets/136346/51b037f5-4712-4bbc-b1f5-034b6dc1af8b)

![image](https://github.com/mong/mongts/assets/136346/797b0654-e4db-4bb0-ad92-3eafa5d9400f)

2024-04-11 14:04 UTC, arnfinn commented on packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx
> +            {regData.registerShortName}
Hvorfor har du byttet til kortnavn her? Jeg får heller ikke opp noe navn på register over tabell lenger. Kjører med qa-api, men mulig det er en brukerfeil.

2024-04-11 14:04 UTC, arnfinn commented
> @arnfinn er denne reviewed?

Nå er den det:)

2024-04-12 11:08 UTC, Stein-Kato commented on packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx
> +            {regData.registerShortName}
Såvidt jeg klarer å se så har ikke qa-databasenb `short_name`-kolonnen i `ind`-tabellen, så den sorterer kanskje på `null`-verdier isteden. Har du prøvd med prod-api? 

Sjekket med @larstun om registernavn i tabell, og det skal være fullt navn der. Fikser det.

2024-04-12 11:21 UTC, Stein-Kato commented on packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx
> +            {regData.registerShortName}
Kontrabeskjed, API-et er oppdatert, så det må testes lokalt

2024-04-16 12:29 UTC, arnfinn approved these changes

2024-04-16 12:36 UTC, arnfinn commented
@Stein-Kato Jeg er usikker på om registre ble sortert her. Jeg har hjerneslag øverst. Skulle vel vært ablanor?

2024-04-16 12:38 UTC, Stein-Kato commented
> @Stein-Kato Jeg er usikker på om registre ble sortert her. Jeg har hjerneslag øverst. Skulle vel vært ablanor?

Registrene ble sortert etter register-id. Det manglet et sett parenteser i compare-funksjonen. Skal være ordnet i siste commit.

2024-04-17 06:49 UTC, larstun commented
@Stein-Kato er denne klar til å merges nå?

2024-04-17 06:51 UTC, Stein-Kato commented
> @Stein-Kato er denne klar til å merges nå?

Ja

2024-04-17 06:51 UTC, merged