Prøvde å forbedre footeren, spesielt med tanke på de 4 logoene til Helseatlas-siden
mong/mongts pull request #2772
Opened 2024-07-03 08:25 UTC by Uglemat

* Byttet til MUI Grid v2 (som vi allerede bruker andre plasser)
* La alle logoer på en linje, i stedet for å ha de litt her og der. Dette ser bedre ut for helseatlas-sidene, som har 4 logoer. For kvalitetsregister-sidene gjør det at HN-logoen kommer ved siden av SKDE-logoen, så denne endringen må nok diskuteres.

2024-07-03 11:31 UTC, Stein-Kato requested changes
Bunnen av footeren blir for smal når vinduet blir veldig bredt

![image](https://github.com/mong/mongts/assets/64078729/0584c781-4664-4b06-8b38-c23a69062c77)

2024-08-06 06:21 UTC, larstun approved these changes
Ser sikkert bra ut :)

2024-08-06 12:13 UTC, Uglemat commented
Det virker som @Stein-Kato må bekrefte at de forespurte endringene er gjort før denne PR kan merges

2024-08-07 06:08 UTC, Stein-Kato approved these changes

2024-08-07 07:36 UTC, merged