Styling av sykehusprofil
mong/mongts pull request #2863
Opened 2024-08-14 09:38 UTC by Stein-Kato

2024-08-14 11:41 UTC, arnfinn commented
Gammel versjon

![image](https://github.com/user-attachments/assets/f2aff8d0-b05b-4a19-9723-cb630a1eee45)

![image](https://github.com/user-attachments/assets/8d082364-7427-4f21-95c6-09e8c4b702e0)

Ny versjon

![image](https://github.com/user-attachments/assets/d9529900-03bc-4cb6-8333-2af2846b1d26)

![image](https://github.com/user-attachments/assets/f15c8e09-ae9e-4455-9429-dc54e9c651d0)

2024-08-14 11:45 UTC, arnfinn commented
Før:
![image](https://github.com/user-attachments/assets/52de81f6-88db-4458-b18e-abfc4be2b1bc)

Etter:
![image](https://github.com/user-attachments/assets/9f4a945c-ddb0-48c3-bf1b-c95399e43033)

2024-08-14 12:04 UTC, arnfinn requested changes
Endringene påvirket de andre nettsidene. Se de to forrige kommentarer.

2024-08-14 12:28 UTC, Stein-Kato commented
> Endringene påvirket de andre nettsidene. Se de to forrige kommentarer.

Fikset

2024-08-15 07:43 UTC, arnfinn commented
Fremdeles noen endringer.

Fra
![image](https://github.com/user-attachments/assets/3a59a42a-3e57-44ee-9e0d-5d2c45ad75d7)

![image](https://github.com/user-attachments/assets/5cb8853b-115f-442b-a927-1cfc596e3c08)

til
![image](https://github.com/user-attachments/assets/4f30061a-fb9d-4bec-b895-4c8117b690ed)

![image](https://github.com/user-attachments/assets/cf565ad4-f788-430a-9dc0-48c9ac84b24d)

2024-08-16 06:49 UTC, arnfinn approved these changes
![hearts-of-happiness-hearts](https://github.com/user-attachments/assets/0433c8f0-6a18-4fc3-ba4a-f79312aea0ca)

2024-08-16 07:09 UTC, merged