Logo på linjeplot i behandlingskvalitet
mong/mongts pull request #3039
Opened 2024-09-02 14:12 UTC by Stein-Kato

![image](https://github.com/user-attachments/assets/316b8cd2-ce46-4272-99ad-1e462480a1ce)

2024-09-03 12:31 UTC, Stein-Kato commented
@arnfinn Klar til sjekk

2024-09-03 12:51 UTC, arnfinn approved these changes

2024-09-03 14:44 UTC, arnfinn requested changes

2024-09-03 14:44 UTC, arnfinn commented on apps/skde/public/img/logos/logo-skde-blaa.svg
Ikke bytt navn på denne. Mister logo i header og footer da.

2024-09-04 06:36 UTC, Stein-Kato commented on apps/skde/public/img/logos/logo-skde-blaa.svg
Fikset

2024-09-04 06:40 UTC, arnfinn approved these changes
La inn en issue om problemene med logo som ikke legges på: https://github.com/mong/mongts/issues/3049

2024-09-04 07:23 UTC, merged