Chips for datakvalitet i målnivåtabell
mong/mongts pull request #3062
Opened 2024-09-04 13:30 UTC by Stein-Kato

2024-09-04 13:49 UTC, arnfinn requested changes

2024-09-04 13:49 UTC, arnfinn commented on packages/qmongjs/src/components/ChipSelection/index.tsx
Denne fila brukes vel ikke enda?

2024-09-05 07:49 UTC, Stein-Kato commented on packages/qmongjs/src/components/ChipSelection/index.tsx
Ble noe rot i greina. Lukker denne og starter på nytt.

2024-09-05 09:53 UTC, arnfinn approved these changes

2024-09-05 13:10 UTC, merged